### PR TITLE
Created contribution.md file

### PR DESCRIPTION
**Pull request by nilisha-jais**

### CODE REVIEW

**Comment by Tejas1510** [comment]
@nilisha-jais just stash all your commits into a single commit 
Else the PR is good to merge

**Comment by nilisha-jais** [comment]
I am completely new to what git stash is as I have never used it before. Can you please help

**Comment by Tejas1510** [comment]
https://git-scm.com/docs/git-stash
This will help you

**Comment by nilisha-jais** [comment]
@Tejas1510 sir facing problem using stash command. Can't you merge it this way only??
When I'll make a pr next time in which multiple file is changed i'll try implementing this method

**Comment by Tejas1510** [comment]
@nilisha-jais ok no worries
Just close this PR and make a new PR where you will add all things required 
This will do

**Comment by nilisha-jais** [comment]
@Tejas1510 bhaiya please check is this what you wanted me to do

**Comment by Tejas1510** [comment]
Great Work @nilisha-jais 
This is what open source will teach you
You fail never quit
Kudos and Happy Coding

**Pull request merged**
