### PR TITLE
Added a Code of Conduct

### PR DESCRIPTION
**Pull request by dhawalyash00**

### CODE REVIEW

**Comment by Tejas1510** [comment]
@dhawalyash00 until the issue isn't assign to you 
You can contribute to it
First comment on the particular issue, I will assign it to you and are you a cross winter of code participant?

**Comment by dhawalyash00** [comment]
> @dhawalyash00 until the issue isn't assign to you
> You can contribute to it
> First comment on the particular issue, I will assign it to you and are you a cross winter of code participant?
sure....assign me the issue
and No...im not a cross winter of code participant.....btw....why ?

**Comment by dhawalyash00** [comment]
have you assigned me the issue already?

**Comment by Tejas1510** [comment]
@dhawalyash00 The Project is a part of Cross winter of code
So I shouldn't allow you but since you have created the PR, I would allow you to contribute to this issue only
Close this PR
Comment on the issue, I would like to work on it and after assignment generate the PR
I would merge it

**Pull request closed without merging**
